server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: service-wallet
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.20:3306/runner-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: MySQL@8888
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.runner.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mapper:
  mappers: com.runner.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

# 支付宝沙箱配置
alipay:
  app-id: 9021000164695198
  private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCPRWdrbVVwyKKffC1g+s1PLZTcxSTKL3zkOKN+JVcJhCK+EGoQ3mxubyQsEs1lL8bmo8MuyXhQSYwBav59dPpgtlBsLUMSbUI/dxUX4OucUTnEBy8V0H8D/1dJOPvwO0nw/p3jA2lpaigZhuBVMHEAaWuuUy7QicCY2K8EFi6G0wny0KsoxggLkjZThnP27TbOfjOg85bcnfPW8UKle9lj76ZnQImvB7ellrYjdE5iyLHrMdO4EfI/limRpck57fDxr35YRL9L8ysn51iCTzAlb6i5X4kU7FRso3caFOQtYh/siikDNzn+LpMU5dOnxOWiAkNvcBJbQB0HnOhpPKL9AgMBAAECggEAY9remtwoGaRs27Vjt1z2LYI6Z6ir3JM+e54SLUB/Ki3DPS8ZjcpITqv9zQ4Jw8WJ3oQy7HAU//hSsUZOO0iFnVRUNyFQxw4Jh0xLEkp8TIW8Oik7ovufGz0jK/Cgf64C+gmsJ2XgWU1Yx3ne7uEFUWEoYOavET+BUcZsLO/825A3SnJdkGQDactCocTQ3foZNGoNLM9yBZeTEX5U9J3KbEppA1cawj36hMXNTSZH6thdzdWMU7Y00cObhH9PCaxF+/LU4DCsFsQGVyxZmtQeZa/rJeoWIQGTkfNQkR6u5cAfSOq2s3DpwiY1OqsLtLcjE8LZ1AlA+xwrdGmePvm4rQKBgQDwhMXuDBiYqt+01jo+zpvYYINwtZnf9uXF/7PYDuLOQGeGR7mk4P3ipWc5ynYV9EKas05zQM+wuXY6oBk2jGh+dhO+aZyBdvdceMAdvZyVutS7JDVevLls9kZGwn7Ub7xZnoDmVo9zu21uJXWTSTlCVA5KX9iB4oiBFH4+Ls8wVwKBgQCYfjOsqIq7j8430TOCpb+TfaYC6cFZeXsKa2T+SptbpHRibTeCk8IIgKVk8AcCDjO450lw1dmK8xeO/iHhn7iYsB5gX8spfCOqnh9oJcans0oCmzpAEquRPRpOfJd9lRZQcMMZVZFu+vz1sfAfjN+sjAkGpaMdgjAnnMIvkxBiywKBgFOuvnbuenhTq3Xtu2Iy3IJSQikq5hjIfHWBW/9mXn9IZTyRJAQ7y9nZlqrCyIcm7y2ICVmMSTbBsGMBZQRXoduuFXyAnlVlIPdpg95VJG/sCyv5kyAdJZ7FqPnhneMn5S6BOXPq1gp8Qby7B8dxCJ0NRdOWuWund7sBeFMGUkwNAoGARBU0ZQXqysrtuyX/5XizC9qxX+OVm6kNMh24vX/51PSbscYpXncxzjIBpgs0VcqZdRhuRZ50vgDCp+j2n5F8DU+0gDrErgTqt6ZZR1p2UzFM/dToMOslBndNY3Vk/YCuscNml80IXZBZmCiVmMCArLzo2rrhFK+naEgouqziR/kCgYBmOe3IqdSoE8YlPvMLl3iv09oRRAYfTzIGf4sbw15gR1+IBYuy+iwzzNwYY58qb30egfUQsG8xNj33Skfa8nD+gwbJzYgKYCI5accMe/zDXLSBZoV0fzW/eKvVwiyt1q8D3OsQ1Bllr5bFrYGfo9Hps6mKf3A+eS9nDllU1+gd2A==
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimIQw8f6yNwaJdaX0T78hbKzM4SR5qZZUjKKabc8nkbXoXdiXUR4tP/TQ1GtpwIjjIQCVO0+gvBSzx4UiI6rmVYv5jT0ST6W1+K6QtnWZfa34a/oE/KGFuX6bGp5R8YB3toSKfhLdz1lfvv5ZpT91t2IpkSKSeTAb7it9SHB5ZklHACpzpZ0kPd8Dwmj2pbTpIi7IY9Es2dKmWMlnkYRcv7rKQJ9vYZ1x+c4/BJti+lZJni0bsbhXqgomEc4HhRzf0REox9v5AvZaflZd99D+M58PBZS/5g5wrSDAKNMMTw2Pi5gRbWzabi/j3gg+lODGXZqPOYGmGrPj8Lk3QH9TQIDAQAB
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  sign-type: RSA2
  return-url: http://runner.gzmu.com:9091/runner/portal/wallet.html
  notify-url: http://wallet.runner.gzmu.com:8007/wallet/alipay/notify